sonar.projectKey=lab3-csharp
sonar.projectName=Lab3 CSharp
sonar.projectVersion=1.0
sonar.sources=Lab3.Auth
sonar.tests=Lab3.Auth.Tests
sonar.language=cs
sonar.cs.opencover.reportsPaths=coverage-results/**/coverage.cobertura.xml
sonar.sourceEncoding=UTF-8
sonar.host.url=http://localhost:9000
