sonar.projectKey=lab3-csharp
sonar.working.directory=C:\\Users\\user\\Desktop\\lab3-csharp\\.sonarqube\\out\\.sonar
sonar.projectBaseDir=C:\\Users\\user\\Desktop\\lab3-csharp
sonar.pullrequest.cache.basepath=C:\\Users\\user\\Desktop\\lab3-csharp
sonar.sources=\
"C:\\Users\\user\\Desktop\\lab3-csharp\\.vs\\ProjectSettings.json",\
"C:\\Users\\user\\Desktop\\lab3-csharp\\.vs\\VSWorkspaceState.json",\
"C:\\Users\\user\\Desktop\\lab3-csharp\\.github\\workflows\\ci.yml",\
"C:\\Users\\user\\Desktop\\lab3-csharp\\.vs\\lab3-csharp\\v17\\DocumentLayout.json"

6520AF46-BAF6-4BA3-A812-AB860A784AAC.sonar.projectKey=lab3-csharp:6520AF46-BAF6-4BA3-A812-AB860A784AAC
6520AF46-BAF6-4BA3-A812-AB860A784AAC.sonar.projectName=Lab3.Auth
6520AF46-BAF6-4BA3-A812-AB860A784AAC.sonar.projectBaseDir=C:\\Users\\user\\Desktop\\lab3-csharp\\Lab3.Auth
6520AF46-BAF6-4BA3-A812-AB860A784AAC.sonar.sourceEncoding=utf-8
6520AF46-BAF6-4BA3-A812-AB860A784AAC.sonar.tests=
6520AF46-BAF6-4BA3-A812-AB860A784AAC.sonar.sources=\
"C:\\Users\\user\\Desktop\\lab3-csharp\\Lab3.Auth\\Controllers\\AuthController.cs",\
"C:\\Users\\user\\Desktop\\lab3-csharp\\Lab3.Auth\\Program.cs",\
"C:\\Users\\user\\Desktop\\lab3-csharp\\Lab3.Auth\\Services\\AuthService.cs",\
"C:\\Users\\user\\Desktop\\lab3-csharp\\Lab3.Auth\\obj\\Debug\\net9.0\\Lab3.Auth.GlobalUsings.g.cs",\
"C:\\Users\\user\\Desktop\\lab3-csharp\\Lab3.Auth\\obj\\Debug\\net9.0\\.NETCoreApp,Version=v9.0.AssemblyAttributes.cs",\
"C:\\Users\\user\\Desktop\\lab3-csharp\\Lab3.Auth\\obj\\Debug\\net9.0\\Lab3.Auth.AssemblyInfo.cs",\
"C:\\Users\\user\\Desktop\\lab3-csharp\\Lab3.Auth\\appsettings.Development.json",\
"C:\\Users\\user\\Desktop\\lab3-csharp\\Lab3.Auth\\appsettings.json",\
"C:\\Users\\user\\Desktop\\lab3-csharp\\Lab3.Auth\\Lab3.Auth.http",\
"C:\\Users\\user\\Desktop\\lab3-csharp\\Lab3.Auth\\Properties\\launchSettings.json",\
"C:\\Users\\user\\Desktop\\lab3-csharp\\Lab3.Auth\\obj\\Lab3.Auth.csproj.nuget.dgspec.json",\
"C:\\Users\\user\\Desktop\\lab3-csharp\\Lab3.Auth\\obj\\project.assets.json",\
"C:\\Users\\user\\Desktop\\lab3-csharp\\Lab3.Auth\\bin\\Debug\\net9.0\\appsettings.Development.json",\
"C:\\Users\\user\\Desktop\\lab3-csharp\\Lab3.Auth\\bin\\Debug\\net9.0\\appsettings.json",\
"C:\\Users\\user\\Desktop\\lab3-csharp\\Lab3.Auth\\bin\\Debug\\net9.0\\Lab3.Auth.deps.json",\
"C:\\Users\\user\\Desktop\\lab3-csharp\\Lab3.Auth\\bin\\Debug\\net9.0\\Lab3.Auth.runtimeconfig.json",\
"C:\\Users\\user\\Desktop\\lab3-csharp\\Lab3.Auth\\bin\\Debug\\net9.0\\Lab3.Auth.staticwebassets.endpoints.json",\
"C:\\Users\\user\\Desktop\\lab3-csharp\\Lab3.Auth\\obj\\Debug\\net9.0\\Lab3.Auth.sourcelink.json",\
"C:\\Users\\user\\Desktop\\lab3-csharp\\Lab3.Auth\\obj\\Debug\\net9.0\\rjsmcshtml.dswa.cache.json",\
"C:\\Users\\user\\Desktop\\lab3-csharp\\Lab3.Auth\\obj\\Debug\\net9.0\\rjsmrazor.dswa.cache.json",\
"C:\\Users\\user\\Desktop\\lab3-csharp\\Lab3.Auth\\obj\\Debug\\net9.0\\rpswa.dswa.cache.json",\
"C:\\Users\\user\\Desktop\\lab3-csharp\\Lab3.Auth\\obj\\Debug\\net9.0\\staticwebassets.build.endpoints.json",\
"C:\\Users\\user\\Desktop\\lab3-csharp\\Lab3.Auth\\obj\\Debug\\net9.0\\staticwebassets.build.json"

6520AF46-BAF6-4BA3-A812-AB860A784AAC.sonar.cs.analyzer.projectOutPaths=\
"C:\\Users\\user\\Desktop\\lab3-csharp\\.sonarqube\\out\\0",\
"C:\\Users\\user\\Desktop\\lab3-csharp\\.sonarqube\\out\\2"
6520AF46-BAF6-4BA3-A812-AB860A784AAC.sonar.cs.roslyn.reportFilePaths=\
"C:\\Users\\user\\Desktop\\lab3-csharp\\.sonarqube\\out\\0\\Issues.json",\
"C:\\Users\\user\\Desktop\\lab3-csharp\\.sonarqube\\out\\2\\Issues.json"
6520AF46-BAF6-4BA3-A812-AB860A784AAC.sonar.cs.scanner.telemetry=\
"C:\\Users\\user\\Desktop\\lab3-csharp\\.sonarqube\\out\\0\\Telemetry.json",\
"C:\\Users\\user\\Desktop\\lab3-csharp\\.sonarqube\\out\\2\\Telemetry.json"

6520AF46-BAF6-4BA3-A812-AB860A784AAC.sonar.working.directory=C:\\Users\\user\\Desktop\\lab3-csharp\\.sonarqube\\out\\.sonar\\mod0
4AB90D16-BFFF-4C09-8AEA-1E922BB724F6.sonar.projectKey=lab3-csharp:4AB90D16-BFFF-4C09-8AEA-1E922BB724F6
4AB90D16-BFFF-4C09-8AEA-1E922BB724F6.sonar.projectName=Lab3.Auth.Tests
4AB90D16-BFFF-4C09-8AEA-1E922BB724F6.sonar.projectBaseDir=C:\\Users\\user\\Desktop\\lab3-csharp\\Lab3.Auth.Tests
4AB90D16-BFFF-4C09-8AEA-1E922BB724F6.sonar.sourceEncoding=utf-8
4AB90D16-BFFF-4C09-8AEA-1E922BB724F6.sonar.sources=
4AB90D16-BFFF-4C09-8AEA-1E922BB724F6.sonar.tests=\
"C:\\Users\\user\\Desktop\\lab3-csharp\\Lab3.Auth.Tests\\.vs\\ProjectSettings.json",\
"C:\\Users\\user\\Desktop\\lab3-csharp\\Lab3.Auth.Tests\\.vs\\VSWorkspaceState.json",\
"C:\\Users\\user\\Desktop\\lab3-csharp\\Lab3.Auth.Tests\\obj\\Lab3.Auth.Tests.csproj.nuget.dgspec.json",\
"C:\\Users\\user\\Desktop\\lab3-csharp\\Lab3.Auth.Tests\\obj\\project.assets.json",\
"C:\\Users\\user\\Desktop\\lab3-csharp\\Lab3.Auth.Tests\\.vs\\Lab3.Auth.Tests\\v17\\DocumentLayout.backup.json",\
"C:\\Users\\user\\Desktop\\lab3-csharp\\Lab3.Auth.Tests\\.vs\\Lab3.Auth.Tests\\v17\\DocumentLayout.json",\
"C:\\Users\\user\\Desktop\\lab3-csharp\\Lab3.Auth.Tests\\bin\\Debug\\net9.0\\appsettings.Development.json",\
"C:\\Users\\user\\Desktop\\lab3-csharp\\Lab3.Auth.Tests\\bin\\Debug\\net9.0\\appsettings.json",\
"C:\\Users\\user\\Desktop\\lab3-csharp\\Lab3.Auth.Tests\\bin\\Debug\\net9.0\\Lab3.Auth.deps.json",\
"C:\\Users\\user\\Desktop\\lab3-csharp\\Lab3.Auth.Tests\\bin\\Debug\\net9.0\\Lab3.Auth.runtimeconfig.json",\
"C:\\Users\\user\\Desktop\\lab3-csharp\\Lab3.Auth.Tests\\bin\\Debug\\net9.0\\Lab3.Auth.staticwebassets.endpoints.json",\
"C:\\Users\\user\\Desktop\\lab3-csharp\\Lab3.Auth.Tests\\bin\\Debug\\net9.0\\Lab3.Auth.Tests.deps.json",\
"C:\\Users\\user\\Desktop\\lab3-csharp\\Lab3.Auth.Tests\\bin\\Debug\\net9.0\\Lab3.Auth.Tests.runtimeconfig.json",\
"C:\\Users\\user\\Desktop\\lab3-csharp\\Lab3.Auth.Tests\\bin\\Debug\\net9.0\\MvcTestingAppManifest.json",\
"C:\\Users\\user\\Desktop\\lab3-csharp\\Lab3.Auth.Tests\\obj\\Debug\\net9.0\\Lab3.Auth.Tests.sourcelink.json",\
"C:\\Users\\user\\Desktop\\lab3-csharp\\Lab3.Auth.Tests\\obj\\Debug\\net9.0\\MvcTestingAppManifest.json",\
"C:\\Users\\user\\Desktop\\lab3-csharp\\Lab3.Auth.Tests\\AuthControllerTests.cs",\
"C:\\Users\\user\\Desktop\\lab3-csharp\\Lab3.Auth.Tests\\AuthServiceTests.cs",\
"C:\\Users\\user\\Desktop\\lab3-csharp\\Lab3.Auth.Tests\\UnitTest1.cs",\
"C:\\Users\\user\\Desktop\\lab3-csharp\\Lab3.Auth.Tests\\coverage-results\\8da0776b-7d0b-46aa-98a8-992bdcaa0425\\coverage.cobertura.xml",\
"C:\\Users\\user\\Desktop\\lab3-csharp\\Lab3.Auth.Tests\\coverage-results\\d523fcdb-0fb9-4938-b74b-fa000d0688d4\\coverage.cobertura.xml"

4AB90D16-BFFF-4C09-8AEA-1E922BB724F6.sonar.cs.analyzer.projectOutPaths=\
"C:\\Users\\user\\Desktop\\lab3-csharp\\.sonarqube\\out\\1",\
"C:\\Users\\user\\Desktop\\lab3-csharp\\.sonarqube\\out\\3"
4AB90D16-BFFF-4C09-8AEA-1E922BB724F6.sonar.cs.roslyn.reportFilePaths=\
"C:\\Users\\user\\Desktop\\lab3-csharp\\.sonarqube\\out\\1\\Issues.json",\
"C:\\Users\\user\\Desktop\\lab3-csharp\\.sonarqube\\out\\3\\Issues.json"
4AB90D16-BFFF-4C09-8AEA-1E922BB724F6.sonar.cs.scanner.telemetry=\
"C:\\Users\\user\\Desktop\\lab3-csharp\\.sonarqube\\out\\1\\Telemetry.json",\
"C:\\Users\\user\\Desktop\\lab3-csharp\\.sonarqube\\out\\3\\Telemetry.json"

4AB90D16-BFFF-4C09-8AEA-1E922BB724F6.sonar.working.directory=C:\\Users\\user\\Desktop\\lab3-csharp\\.sonarqube\\out\\.sonar\\mod1
sonar.host.url=http://localhost:9000
sonar.cs.opencover.reportsPaths=coverage-results/**/coverage.cobertura.xml
sonar.exclusions=coverage-results/**/coverage.cobertura.xml
sonar.visualstudio.enable=false

sonar.modules=6520AF46-BAF6-4BA3-A812-AB860A784AAC,4AB90D16-BFFF-4C09-8AEA-1E922BB724F6

